controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    
    # Controllers for MoveIt integration
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    # This is the key controller that MoveIt will use
    fr3_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
      - fr3_finger_joint1
      - fr3_finger_joint2

# FR3 Arm Controller for MoveIt trajectory execution
fr3_arm_controller:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      fr3_joint1: { trajectory: 0.1, goal: 0.05 }
      fr3_joint2: { trajectory: 0.1, goal: 0.05 }
      fr3_joint3: { trajectory: 0.1, goal: 0.05 }
      fr3_joint4: { trajectory: 0.1, goal: 0.05 }
      fr3_joint5: { trajectory: 0.1, goal: 0.05 }
      fr3_joint6: { trajectory: 0.1, goal: 0.05 }
      fr3_joint7: { trajectory: 0.1, goal: 0.05 }