controller_manager:
  ros__parameters:
    update_rate: 100  # Hz (matches UR)

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fr3_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    fr3_gripper_controller:
      type: position_controllers/JointGroupPositionController


fr3_arm_controller:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      fr3_joint1: { trajectory: 0.2, goal: 0.1 }
      fr3_joint2: { trajectory: 0.2, goal: 0.1 }
      fr3_joint3: { trajectory: 0.2, goal: 0.1 }
      fr3_joint4: { trajectory: 0.2, goal: 0.1 }
      fr3_joint5: { trajectory: 0.2, goal: 0.1 }
      fr3_joint6: { trajectory: 0.2, goal: 0.1 }
      fr3_joint7: { trajectory: 0.2, goal: 0.1 }


fr3_gripper_controller:
  ros__parameters:
    joints:
      - fr3_finger_joint1
      - fr3_finger_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity