controller_manager:
  ros__parameters:
    update_rate: 100
    
    ur_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    robotiq_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ur_manipulator_controller.ros__parameters:
      joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
        
    robotiq_gripper_controller.ros__parameters:
      joints:
        - robotiq_85_left_knuckle_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity